termine_array = new Array();

termine_array = [
		{
			'datum'			: "18.07.2015 19:00",
			'title'			: 'Bürgerversammlung',
			'teaser'		: "",
			'location'		: "Stadthalle Neuss",
		},
		{
			'datum'			: "01.08.2015 19:00",
			'title'			: 'Majorsehrenabend',
			'teaser'		: "Große Korpsversammlung Jubilarehrung, anschl. Heimgeleit des Majors und Biwak am Grenadier-Schützen-Denkmal",
			'location'		: "Stadthalle Neuss",
		},
		{
			'datum'			: "03.08.2015 19:00",
			'title'			: 'Marschübung',
			'teaser'		: "",
			'location'		: "Parkplatz Rennbahn / Globe Theater",
		},
		{
			'datum'			: "08.08.2015 18:30",
			'title'			: 'Oberstehrenabend',
			'teaser'		: "",
			'location'		: "Stadthalle Neuss",
		},
		{
			'datum'			: "10.08.2015 20:00",
			'title'			: 'Zugführerbesprechung',
			'teaser'		: "",
			'location'		: "Marienhaus, Kapitelstaße 36",
		},
		{
			'datum'			: "15.08.2015 17:30",
			'title'			: 'Königsehrenabend',
			'teaser'		: "",
			'location'		: "Stadthalle Neuss",
		},
		{
			'datum'			: "23.08.2015 11:00",
			'title'			: 'Promenadenkonzert des NGK',
			'teaser'		: "",
			'location'		: "Platz am Weißen Haus",
		},
		{
			'datum'			: "24.08.2015 17:30",
			'title'			: 'Fackelbesichtigung',
			'teaser'		: "",
			'location'		: "Fackelbauhalle Zietzschmannhalle",
		},
		{
			'datum'			: "28.08.2015 17:00",
			'title'			: 'Kirmesplatz Eröffnung',
			'teaser'		: "",
			'location'		: "Hessentorbrücke",
		},
		{
			'datum'			: "28.08.2015 - 01.09.2015",
			'title'			: "Neusser Bürger-Schützenfest",
			'teaser'		: "",
			'location'		: "",
		},
		{
			'datum'			: "05.09.2015 18:00",
			'title'			: 'Krönungszug / Krönungsball',
			'teaser'		: "",
			'location'		: "Stadthalle Neuss",
		},
		{
			'datum'			: "15.09.2015 20:00",
			'title'			: 'Chargiertenversammlung',
			'teaser'		: "",
			'location'		: "Marienhaus, Kapitelstraße 36",
		},
		{
			'datum'			: "26.09.2015 18:00",
			'title'			: 'NGK Oktoberfest',
			'teaser'		: "",
			'location'		: "TÜV Platz Neuss",
		},
		{
			'datum'			: "25.10.2015 09:30",
			'title'			: 'Herbstkorpsschießen',
			'teaser'		: "",
			'location'		: "S.S.V. Neuss 1962 e.V., Further Straße (Eingang hinter dem Parkhaus rechts)",
		},
		{
			'datum'			: "13.11.2015 20:00",
			'title'			: 'Jahreshauptversammlung NGK',
			'teaser'		: "",
			'location'		: "Marienhaus, Kapitelstraße 36",
		},
		{
			'datum'			: "15.11.2015 11:30",
			'title'			: 'Volkstrauertag',
			'teaser'		: "",
			'location'		: "Hauptfriedhof, Rheydter Straße",
		},
		{
			'datum'			: "20.11.2015 20:00",
			'title'			: 'Jahreshauptversammlung NBS',
			'teaser'		: "Neusser Bürger-Schützen-Verein",
			'location'		: "Sparkassen – Forum Haus II, Sparkasse Neuss Michaelstraße",
		},
		
		/* 2016 */
		
		{
			'datum'			: "06.03.2016 09:30",
			'title'			: 'Korpsschießen',
			'teaser'		: "",
			'location'		: "Scheibenstand, Scheibendamm",
		},
		{
			'datum'			: "22.04.2016 20:00",
			'title'			: 'Chargiertenversammlung',
			'teaser'		: "",
			'location'		: "Marienhaus, Kapitelstraße 36",
		},
		{
			'datum'			: "10.05.2016 20:00",
			'title'			: 'Fackelbaubesprechung',
			'teaser'		: "",
			'location'		: "Scheibenstand, Scheibendamm",
		},
		{
			'datum'			: "26.06.2016 10:00",
			'title'			: 'Patronatstag',
			'teaser'		: "",
			'location'		: "Heilige Messe – St. Marien Umzug zum Foyer Rheinisches Landestheater",
		},
		{
			'datum'			: "16.07.2016 19:00",
			'title'			: 'Bürgerversammlung',
			'teaser'		: "",
			'location'		: "Stadthalle Neuss",
		},
		{
			'datum'			: "30.07.2016 19:00",
			'title'			: 'Majorsehrenabend',
			'teaser'		: "Große Korpsversammlung Jubilarehrung, anschl. Heimgeleit des Majors und Biwak am Grenadier-Schützen-Denkmal",
			'location'		: "Stadthalle Neuss",
		},
		{
			'datum'			: "01.08.2016 19:00",
			'title'			: 'Marschübung',
			'teaser'		: "",
			'location'		: "Parkplatz Rennbahn / Globe Theater",
		},
		{
			'datum'			: "06.08.2016 18:30",
			'title'			: 'Oberstehrenabend',
			'teaser'		: "",
			'location'		: "Stadthalle Neuss",
		},
		{
			'datum'			: "08.08.2016 20:00",
			'title'			: 'Zugführerbesprechung',
			'teaser'		: "",
			'location'		: "Marienhaus, Kapitelstaße 36",
		},
		{
			'datum'			: "12.08.2016 17:30",
			'title'			: 'Königsehrenabend',
			'teaser'		: "",
			'location'		: "Stadthalle Neuss",
		},
		{
			'datum'			: "21.08.2016 11:00",
			'title'			: 'Promenadenkonzert des NGK',
			'teaser'		: "",
			'location'		: "Platz am Weißen Haus",
		},
		{
			'datum'			: "22.08.2016 17:30",
			'title'			: 'Fackelbesichtigung',
			'teaser'		: "",
			'location'		: "Fackelbauhalle Zietzschmannhalle",
		},
		{
			'datum'			: "26.08.2016 17:00",
			'title'			: 'Kirmesplatz Eröffnung',
			'teaser'		: "",
			'location'		: "Hessentorbrücke",
		},
		{
			'datum'			: "27.08.2016 - 30.08.2016",
			'title'			: "Neusser Bürger-Schützenfest",
			'teaser'		: "",
			'location'		: "",
		},
		{
			'datum'			: "03.09.2016 18:00",
			'title'			: 'Krönungszug / Krönungsball',
			'teaser'		: "",
			'location'		: "Stadthalle Neuss",
		},
		{
			'datum'			: "13.09.2016 20:00",
			'title'			: 'Chargiertenversammlung',
			'teaser'		: "",
			'location'		: "Marienhaus, Kapitelstraße 36",
		},
		{
			'datum'			: "24.09.2016 18:00",
			'title'			: 'NGK Oktoberfest',
			'teaser'		: "",
			'location'		: "TÜV Platz Neuss",
		},
		{
			'datum'			: "23.10.2016 09:30",
			'title'			: 'Herbstkorpsschießen',
			'teaser'		: "",
			'location'		: "S.S.V. Neuss 1962 e.V., Further Straße (Eingang hinter dem Parkhaus rechts)",
		},
		{
			'datum'			: "11.11.2016 20:00",
			'title'			: 'Jahreshauptversammlung NGK',
			'teaser'		: "",
			'location'		: "Marienhaus, Kapitelstraße 36",
		},
		{
			'datum'			: "13.11.2016 11:30",
			'title'			: 'Volkstrauertag',
			'teaser'		: "",
			'location'		: "Hauptfriedhof, Rheydter Straße",
		},
		{
			'datum'			: "18.11.2016 20:00",
			'title'			: 'Jahreshauptversammlung NBS',
			'teaser'		: "Neusser Bürger-Schützen-Verein",
			'location'		: "Sparkassen – Forum Haus II, Sparkasse Neuss Michaelstraße",
		},
	];

