termine_array = new Array();

termine_array = [
		{
			'datum'			: "20.03.2018 20:00",
			'title'			: 'Fackelbaubesprechung',
			'teaser'		: "",
			'location'		: "Marienhaus, Kapitelstraße 36",
		},
		{
			'datum'			: "14.04.2018 13:00",
			'title'			: 'Korpsschießen',
			'teaser'		: "",
			'location'		: "Scheibenstand, Scheibendamm",
		},
		{
			'datum'			: "15.05.2018 20:00",
			'title'			: 'Chargiertenversammlung',
			'teaser'		: "",
			'location'		: "Marienhaus, Kapitelstraße 36",
		},
		{ 	
			'datum'			: "24.06.2018 10:00",
			'title'			: 'Patronatstag',
			'teaser'		: "Heilige Messe - St. Marien Umzug zum Foyer Rheinisches Landestheater musikalischer Frühschoppen Siegerehrung Korpsschießen, Ehrungen, Zuganmeldung Schützenfest 2018",
			'location'		: "St. Marien",
		},
		{
			'datum'			: "14.07.2018 19:00",
			'title'			: 'Bürgerversammlung',
			'teaser'		: "",
			'location'		: "Stadthalle Neuss",
		},
		{
			'datum'			: "28.07.2018 19:00",
			'title'			: 'Majorsehrenabend',
			'teaser'		: "Stadthalle Neuss, Große Korpsversammlung Jubilarehrung, anschl. Heimgeleit des Majors und Biwak am Grenadier-Schützen-Denkmal ",
			'location'		: "Stadthalle Neuss",
		},
		{
			'datum'			: "30.07.2018 19:00",
			'title'			: 'Marschübung (bei Bedarf)',
			'teaser'		: "",
			'location'		: "Parkplatz Rennbahn / Globe Theater",
		},
		{
			'datum'			: "04.08.2018 18:30",
			'title'			: 'Oberstehrenabend',
			'teaser'		: "",
			'location'		: "Stadthalle Neuss",
		},
		{
			'datum'			: "06.08.2018 20:00",
			'title'			: 'Zugführerbesprechung',
			'teaser'		: "",
			'location'		: "Marienhaus, Kapitelstaße 36",
		},
		{
			'datum'			: "11.08.2018 17:30",
			'title'			: 'Königsehrenabend',
			'teaser'		: "",
			'location'		: "Stadthalle Neuss",
		},
		{
			'datum'			: "19.08.2018 11:00",
			'title'			: 'Promenadenkonzert des NGK',
			'teaser'		: "",
			'location'		: "Platz am Weißen Haus",
		},
		{
			'datum'			: "20.08.2018 17:30",
			'title'			: 'Fackelbesichtigung',
			'teaser'		: "",
			'location'		: "Fackelbauhalle Zietzschmannhalle",
		},
		{
			'datum'			: "24.08.2018 17:00",
			'title'			: 'Kirmesplatz Eröffnung',
			'teaser'		: "",
			'location'		: "Hessentorbrücke",
		},
		{
			'datum'			: "25.08.2018 12:00 - 28.08.2018 23:59",
			'title'			: "Neusser Bürger-Schützenfest",
			'teaser'		: "25.08.2018 - 28.08.2018",
			'location'		: "",
		},
		{
			'datum'			: "01.09.2018 18:00 - 01.09.2018 20:00",
			'title'			: 'Krönungszug / Krönungsball',
			'teaser'		: "Abmarsch der Chargierten",
			'location'		: "Stadthalle Neuss",
		},
		{
			'datum'			: "11.09.2018 20:00",
			'title'			: 'Chargiertenversammlung',
			'teaser'		: "",
			'location'		: "Marienhaus, Kapitelstraße 36",
		},
		{
			'datum'			: "13.09.2018 00:00 - 19.09.2018 23:59",
			'title'			: 'Steubenparade New York',
			'teaser'		: "13.09.2018 - 19.09.2018",
			'location'		: "",
		},
		{
			'datum'			: "02.10.2018 17:00",
			'title'			: 'Schützen-Wiesn - Oktoberfest mit BRINGS',
			'teaser'		: "",
			'location'		: "Festzelt auf dem Rennbahn Park",
		},
		{
			'datum'			: "18.11.2018 11:30",
			'title'			: 'Volkstrauertag',
			'teaser'		: "",
			'location'		: "Hauptfriedhof, Rheydter Straße",
		},
		{
			'datum'			: "23.11.2018 20:00",
			'title'			: 'Jahreshauptversammlung',
			'teaser'		: "Neusser Bürger-Schützen-Verein",
			'location'		: "Sparkassen – Forum Haus II, Sparkasse Neuss Michaelstraße",
		},
		{
			'datum'			: "01.02.2019 20:00",
			'title'			: 'NGK-Jahreshauptversammlung',
			'teaser'		: "",
			'location'		: "Marienhaus, Kapitelstraße 36",
		},
		{
			'datum'			: "26.03.2019 20:00",
			'title'			: 'Fackelbaubesprechung',
			'teaser'		: "",
			'location'		: "Marienhaus, Kapitelstraße 36",
		},
		{
			'datum'			: "06.04.2019 13:00",
			'title'			: 'Korpsschießen',
			'teaser'		: "",
			'location'		: "Scheibenstand, Scheibendamm",
		},
		{
			'datum'			: "14.05.2019 20:00",
			'title'			: 'Chargiertenversammlung',
			'teaser'		: "",
			'location'		: "Marienhaus, Kapitelstraße 36",
		},
		{ 	
			'datum'			: "30.06.2019 10:00",
			'title'			: 'Patronatstag',
			'teaser'		: "Heilige Messe - St. Marien Umzug zum Foyer Rheinisches Landestheater musikalischer Frühschoppen Siegerehrung Korpsschießen, Ehrungen, Zuganmeldung Schützenfest 2018",
			'location'		: "St. Marien",
		},
		{
			'datum'			: "13.07.2019 19:00",
			'title'			: 'Bürgerversammlung',
			'teaser'		: "",
			'location'		: "Stadthalle Neuss",
		},	
		
		{
			'datum'			: "27.07.2019 19:00",
			'title'			: 'Majorsehrenabend',
			'teaser'		: "Stadthalle Neuss, Große Korpsversammlung Jubilarehrung, anschl. Heimgeleit des Majors und Biwak am Grenadier-Schützen-Denkmal ",
			'location'		: "Stadthalle Neuss",
		},
		{
			'datum'			: "29.07.2019 19:00",
			'title'			: 'Marschübung (bei Bedarf)',
			'teaser'		: "",
			'location'		: "Parkplatz Rennbahn / Globe Theater",
		},
		
		{
			'datum'			: "03.08.2019 18:30",
			'title'			: 'Oberstehrenabend',
			'teaser'		: "",
			'location'		: "Stadthalle Neuss",
		},
		{
			'datum'			: "05.08.2019 20:00",
			'title'			: 'Zugführerbesprechung',
			'teaser'		: "",
			'location'		: "Marienhaus, Kapitelstaße 36",
		},
		{
			'datum'			: "10.08.2019 17:30",
			'title'			: 'Königsehrenabend',
			'teaser'		: "",
			'location'		: "Stadthalle Neuss",
		},
		{
			'datum'			: "19.08.2019 11:00",
			'title'			: 'Promenadenkonzert des NGK',
			'teaser'		: "",
			'location'		: "Platz am Weißen Haus",
		},		
		{
			'datum'			: "19.08.2019 17:30",
			'title'			: 'Fackelbesichtigung',
			'teaser'		: "",
			'location'		: "Fackelbauhalle Zietzschmannhalle",
		},
		{
			'datum'			: "23.08.2019 17:00",
			'title'			: 'Kirmesplatz Eröffnung',
			'teaser'		: "",
			'location'		: "Hessentorbrücke",
		},
		{
			'datum'			: "24.08.2019 12:00 - 27.08.2019 23:59",
			'title'			: "Neusser Bürger-Schützenfest",
			'teaser'		: "24.08.2018 - 24.08.2018",
			'location'		: "",
		},
		{
			'datum'			: "31.08.2019 18:00 - 31.08.2019 20:00",
			'title'			: 'Krönungszug / Krönungsball',
			'teaser'		: "Abmarsch der Chargierten",
			'location'		: "Stadthalle Neuss",
		},
		{
			'datum'			: "10.09.2018 20:00",
			'title'			: 'Chargiertenversammlung',
			'teaser'		: "",
			'location'		: "Marienhaus, Kapitelstraße 36",
		},
		{
			'datum'			: "02.10.2019 18:00",
			'title'			: 'Schützen-Wiesn - Oktoberfest mit Höhner',
			'teaser'		: "",
			'location'		: "Festzelt auf dem Rennbahn Park",
		},
		{
			'datum'			: "17.11.2019 11:30",
			'title'			: 'Volkstrauertag',
			'teaser'		: "",
			'location'		: "Hauptfriedhof, Rheydter Straße",
		},
		{
			'datum'			: "22.11.2019 20:00",
			'title'			: 'Jahreshauptversammlung',
			'teaser'		: "Neusser Bürger-Schützen-Verein",
			'location'		: "Sparkassen – Forum Haus II, Sparkasse Neuss Michaelstraße",
		},

	];

